### ISSUE TITLE
No resemblance

### ISSUE THREAD

**Issue by ghost** [boris-il-forte/beamer-polimi-x#1]
I think it doesn't resemble very well the original theme:

Original theme:
![Template_Nuovo_Page_1](https://user-images.githubusercontent.com/1469713/55746229-81deaa80-5a39-11e9-999a-af772cc5f0b0.png)

Your theme:
![slides_Page_01](https://user-images.githubusercontent.com/1469713/55746255-8f943000-5a39-11e9-8d64-331b7986f474.png)

**Comment by davide-tateo90** [comment]
Sorry, but since I no longer belong to Politecnico di Milano (I've recently finished my Ph.D.), I am not interested in supporting the theme.
You can fork the repository and modify the theme however you want, it's quite simple, just find the right colors.

However, you can find some instructions here:
https://www.polimi.it/fileadmin/user_upload/il_Politecnico/grafica-coordinata/2015_05_11_46xy_manuale_grafica_coordinata.pdf

And you can see that indeed the theme (that, btw, was just fixed by me, not designed) resemble quite closely the one you can find at page 123.

Indeed It is not the case with the ppt theme provided by Polimi site.

However, there are many presentations, at least in the Airlab, that have used the theme or a similar one from this package.
